import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const montserrat = Montserrat( {
  display: "swap",
  subsets: [ "cyrilic" ],
} );

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
    <body
      className={ montserrat.className }
    >
    <main className="bg-[var(--background)] md:rounded-[60px] overflow-hidden">
      <Header />
      { children }
    </main>

    </body>
    </html>
  );
}
