import {Montserrat} from "next/font/google";
import Header from "../components/Header/Header";
import "./globals.css";
import Container from "../components/Container/Container";

const montserrat = Montserrat({
    display: "swap",
    subsets: ["cyrillic"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ru">
        <body
            className={montserrat.className}
        >
            <Container>
        <main className="bg-[var(--background)] md:rounded-[60px] overflow-hidden">
            <Header />
            {children}
        </main>
        </Container>
        </body>
        </html>
    );
}
