import { Montserrat } from 'next/font/google';
import Container from '../components/Container/Container';
import Header from '../components/Header/Header';
import './globals.css';
import { StoreProvider } from './store/StoreProvider';

const montserrat = Montserrat({
  display: 'swap',
  subsets: ['cyrillic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <StoreProvider>
          <Container>
            <Header />
            <main className="relative min-h-screen overflow-x-hidden">{children}</main>
          </Container>
        </StoreProvider>
      </body>
    </html>
  );
}
